import { chromium } from 'playwright'
const browser = await chromium.launch()
const page = await browser.newPage({ viewport: { width: 1280, height: 900 } })
await page.setViewportSize({ width: 1280, height: 900 })
await page.goto('http://localhost:5173/', { waitUntil: 'networkidle' })
await page.screenshot({ path: 'scratch-tests/home.png' })
await page.goto('http://localhost:5173/merge-pdf', { waitUntil: 'networkidle' })
await page.screenshot({ path: 'scratch-tests/merge.png' })
await page.goto('http://localhost:5173/all-tools', { waitUntil: 'networkidle' })
await page.screenshot({ path: 'scratch-tests/all-tools.png' })
await browser.close()
console.log('done')
